# Generated by Django 4.0.3 on 2022-03-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=20)),
                ('cust_email', models.CharField(max_length=20)),
                ('cust_phone_no', models.CharField(max_length=12)),
                ('cust_password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=20)),
                ('seller_email', models.CharField(max_length=20)),
                ('seller_phone_no', models.CharField(max_length=12)),
                ('account_holder', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('IFSC_code', models.CharField(max_length=20)),
                ('seller_password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'seller',
            },
        ),
    ]
