# Generated by Django 4.0.3 on 2022-03-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='products/')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.seller')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
