# Generated by Django 4.0.3 on 2022-03-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_order_seller_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
